### ISSUE TITLE
[Typo] just.. a simple issue

### ISSUE THREAD

**Issue by dongsin-kim** [Qiskit/qiskit-textbook#1]
Hi, I found a trivial typo on the [0.1 Python and Jupyter notebooks]. Could you please check & fix it?

[Step 1]: Please go to - https://community.qiskit.org/textbook/
[Step 2]: Please see - [0.1 Python and Jupyter notebooks] - [ Between Out [7] and In [8] ] 

I think that 'tuple' is missing like below:
[Old]: A major difference between the list and the is that list elements can be changed.
[New]: A major difference between the list and the *tuple* ...

I am not sure this is the right place to report a typo issue. I apologize if this caused any inconvenience.

Best regards,
Dongsin

**Comment by aasfaw** [comment]
Hi @dongsin-kim! Thank you for catching this. You can now open a pull request here to update the textbook. Would you like to submit this change yourself? If not, I can do it too -- just let me know.

**Comment by dongsin-kim** [comment]
Hi @aasfaw-! I have tried to open a new pull request, I noticed that @hay-k Fix typos in ch-prerequisites, ch-gates and ch-states

**Comment by aasfaw** [comment]
Got you. @hay-k's PR is merged now. Thanks for catching this, @dongsin-kim!
