### ISSUE TITLE
Error in Chapter 2.5 "Proving Universality"

### ISSUE THREAD

**Issue by fioyarce** [Qiskit/qiskit-textbook#104]
In this section of the textbook it says:

> We know how to create the unitary $e^{i\frac{\theta}{2} X\otimes X\otimes X}$ from a single qubit $R_x(\theta)$ and two controlled-NOTs.

```python
qc.cx(0,2)
qc.cx(0,1)
qc.rx(theta,0)
qc.cx(0,1)
qc.cx(0,1)
```

>With a few Hadamards, we can do the same for $e^{i\frac{\theta}{2} Z\otimes Z\otimes Z}$.

```python
qc.h(0)
qc.h(1)
qc.h(2)
qc.cx(0,2)
qc.cx(0,1)
qc.rx(theta,0)
qc.cx(0,1)
qc.cx(0,1)
qc.h(2)
qc.h(1)
qc.h(0)
```
For a correct implementation of these transformations I think that one CNOT gate must be applied to the qubit "2" for a symmetric transformation, the implementations must be as follows 
```python
qc.cx(0,2)
qc.cx(0,1)
qc.rx(theta,0)
qc.cx(0,1)
**qc.cx(0,2)** #change qc.cx(0,1) by qc.cx(0,2)
```
and 

```python
qc.h(0)
qc.h(1)
qc.h(2)
qc.cx(0,2)
qc.cx(0,1)
qc.rx(theta,0)
qc.cx(0,1)
**qc.cx(0,2)**  #change qc.cx(0,1) by qc.cx(0,2)
qc.h(2)
qc.h(1)
qc.h(0)
```
Best regards :)

**Comment by Rahps97** [comment]
There is also a typo. replace X with Z
![Screenshot (182)](https://user-images.githubusercontent.com/39730656/80751618-c60e8280-8b47-11ea-8840-48205d73a21d.png)
