### ISSUE TITLE
Teleportation notebook has error loading provider

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-textbook#108]
```python
# First, see what devices we are allowed to use by loading our saved accounts
IBMQ.load_account()
IBMQ.get_provider(hub='ibm-q')
provider.backends()
```
does not work because you are not doing` provider = IBMQ.get_provider(hub='ibm-q')`

**Comment by schwarmco** [comment]
It is actually done in the first block of "1. Simulating the teleportation protocol":

```python
# make the imports that are necessary for our work
import qiskit as qk
from qiskit import ClassicalRegister, QuantumRegister, QuantumCircuit
from qiskit import execute, Aer
from qiskit import IBMQ
from qiskit.tools.visualization import plot_histogram
```

So, when following the Notebook step by step, it's already imported.

But it probably would make sense, to move it down to the first block of "2. Teleportation on a real quantum computer" (the one above in the issue description), as it's not used in the simulation section anyway.
