### ISSUE TITLE
Machine Learning with Qiskit & PyTorch

### ISSUE THREAD

**Issue by amyami187** [Qiskit/qiskit-textbook#11]
We will introduce some basic machine learning concepts using tools from Qiskit and PyTorch!

Contributors: 
Karel Dumon (@dumkar), Amira Abbas (@amyami187), Isaac Turtletaub (@iturtle100), Patrick Huembeli (@patrickhuembeli), Samuel Bosch (@BoschSamuel), Christa Zoufal (@Zoufalc).

**Comment by esobimpe** [comment]
Nice move. Can we not restrict this to pytorch?

**Comment by Zoufalc** [comment]
That is a very good idea. 
We intend to start with PyTorch. Then, the framework can be extended to other platforms as well.

**Comment by esobimpe** [comment]
Sounds like a plan. How can I be part of this? Also interested in QML

**Comment by Zoufalc** [comment]
When we've integrated the first framework feel free to have a look at it and extend it.

**Comment by esobimpe** [comment]
That makes sense.

**Comment by aasfaw** [comment]
Checking in here

Karel Dumon (@dumkar), Amira Abbas (@amyami187), Isaac Turtletaub (@iturtle100), Patrick Huembeli (@PatrickHuembeli), Samuel Bosch (@BoschSamuel), Christa Zoufal (@Zoufalc)

how is the chapter coming along?

**Comment by amyami187** [comment]
@aasfaw I'm so sorry! Been meaning to get to this and will hopefully do so this week :)
