### ISSUE TITLE
BasicAer not imported in vqe-molecules chapter

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-textbook#115]
This fails:
```python
backend = BasicAer.get_backend("statevector_simulator")
```

**Comment by schwarmco** [comment]
Could you maybe give more context?

The imports are right there: 

![image](https://user-images.githubusercontent.com/18698995/73261911-5649ce00-41cd-11ea-97ec-70fc83d63c64.png)

So there must be another problem with BasicAer
