### ISSUE TITLE
On Bernstein–Vazirani

### ISSUE THREAD

**Issue by tbcdebug** [Qiskit/qiskit-textbook#13]
When describing Bernstein–Vazirani (chapter 3.2 section 1a):

>... now the function only returns $1$ for a particular $n$ length bit string $s$, and for all other inputs it returns $0$. In other words, for each input $x$, $f(x) = s \\cdot x \\, \\text{(mod 2)}$.

I think what you are describing before and after **In other words** are actually two different things. The latter one seems to be what commonly known as the oracle in 'Bernstein–Vazirani' and the former one seems to be a searching oracle. (Are you also thinking about Grover's when writing this ^_^)

**Comment by esobimpe** [comment]
@aasfaw issue fixed. see PR #64

**Comment by frankharkins** [comment]
Fixed in commit cbe2b78c24d09683adecf035231f920f2e5dd94e
