### ISSUE TITLE
Bundler Update broke Build Pipeline

### ISSUE THREAD

**Issue by schwarmco** [Qiskit/qiskit-textbook#140]
Bundler updated from 2.1.2 to 2.1.3, thus Travis Pipeline fails.

Working (with 2.1.2): https://travis-ci.com/Qiskit/qiskit-textbook/builds/142865134
Failing (with 2.1.3): https://travis-ci.com/Qiskit/qiskit-textbook/builds/142879253

Relevant Excerpt: 

```bash
$ gem install bundler
Fetching: bundler-2.1.3.gem (100%)
Successfully installed bundler-2.1.3
1 gem installed

$ make install
# Check to see whether bundler is already installed. If not, install it.
if [ hash bundler 2>/dev/null ]; then \
gem install bundler;\
fi
bundle install
Traceback (most recent call last):
	4: from /home/travis/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
	3: from /home/travis/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
	2: from /home/travis/.rvm/gems/ruby-2.5.3/bin/bundle:23:in `<main>'
	1: from /home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
Makefile:14: recipe for target 'install' failed
make: *** [install] Error 1
The command "make install" failed and exited with 2 during .
```

This is (very likely) because in the Gemfile.lock, there's a fixed `BUNDLED WITH 2.1.2`. 
Further Information: https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html

So, either the `BUNDLED WITH` instruction should be removed, or bundler should be pinned to this version with `gem install bundler -v 2.1.2`

**Comment by schwarmco** [comment]
Just to give an update here:

@delapuente's commit https://github.com/Qiskit/qiskit-textbook/commit/c97b55a51a6a1a4347371f96773f054bc69e7f6d currently fixed this issue by adding `gem update --system`.

This upgrades ruby to the current version of `3.1.2` which ships the necessary `2.1.2` bundler by default.

So, currently it works - but as soon, as the latest ruby-version upgrades to a newer bundler, builds may fail again - though it seems ruby >= 2.6 seems to handle that better. 

I can probably close this issue and the PR - just be aware, that this problem may pop up again in the future.

**Comment by aasfaw** [comment]
Perfect. Thanks @schwarmco -- great to have your experience with bundler and travis here. I'll close for now
