### ISSUE TITLE
Error at Bernstein-Vazirani Algorithm

### ISSUE THREAD

**Issue by gdmaru** [Qiskit/qiskit-textbook#144]
If I run below, 

# Run our circuit on the least busy backend. Monitor the execution of the job in the queue
from qiskit.tools.monitor import job_monitor

shots = 1024
job = execute(bvCircuit, backend=backend, shots=shots)

job_monitor(job, interval = 2)

I get below errors.

---------------------------------------------------------------------------

TranspilerError: 'Number of qubits (2) in circuit10 is greater than maximum (1) in the coupling_map'

**Comment by jwoehr** [comment]
At the time that was written, the `ibmq_armonk` QPU wasn't online ... it's funny they named the least powerful QPU for the corporate headquaters ... coincidence? :)
