### ISSUE TITLE
Clicking on chapter titles gives 404 error and going back gives bad formatting

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-textbook#146]
This is the link that gives the 404 error when clicking on the chapter 2 title, for example:

https://delapuente.github.io/qiskit-textbook/ch-quantum-hardware/.html

When going back I see this ill-formatting:

<img width="1198" alt="Screen Shot 2020-01-09 at 6 04 14 AM" src="https://user-images.githubusercontent.com/1249193/72062488-e61eeb00-32a5-11ea-9967-cc6e308e2d0d.png">

for all pages unless I refresh the browser.

**Comment by schwarmco** [comment]
This is the github-pages url from the textbook-fork of @delapuente - it's currently not up to date.
How did you reached this url? Where was it linked from?
