### ISSUE TITLE
'Simulating Molecules using VQE" libraries import issue

### ISSUE THREAD

**Issue by gdmaru** [Qiskit/qiskit-textbook#172]
I was trying to import below
---------------------------------------------------------------
from qiskit.aqua.algorithms import VQE, ExactEigensolver
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from qiskit.chemistry.aqua_extensions.components.variational_forms import UCCSD
from qiskit.aqua.components.variational_forms import RYRZ
from qiskit.chemistry.aqua_extensions.components.initial_states import HartreeFock
from qiskit.aqua.components.optimizers import COBYLA, SPSA, SLSQP
from qiskit import IBMQ, BasicAer, Aer
from qiskit.chemistry.drivers import PySCFDriver, UnitsType
from qiskit.chemistry import FermionicOperator
from qiskit import IBMQ
from qiskit.providers.aer import noise
from qiskit.aqua import QuantumInstance
from qiskit.ignis.mitigation.measurement import CompleteMeasFitter
------------------------------------------------------------------
And I got below errors.
------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-63-6e160eb96cd9> in <module>
      3 get_ipython().run_line_magic('matplotlib', 'inline')
      4 import numpy as np
----> 5 from qiskit.chemistry.aqua_extensions.components.variational_forms import UCCSD
      6 from qiskit.aqua.components.variational_forms import RYRZ
      7 from qiskit.chemistry.aqua_extensions.components.initial_states import HartreeFock

ModuleNotFoundError: No module named 'qiskit.chemistry.aqua_extensions'

**Comment by schwarmco** [comment]
You're right - some components were moved and the textbook got no update there. Here's the correct imports:

```python
from qiskit.aqua.algorithms import VQE, ExactEigensolver
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from qiskit.chemistry.components.variational_forms import UCCSD
from qiskit.chemistry.components.initial_states import HartreeFock
from qiskit.aqua.components.variational_forms import RYRZ
from qiskit.aqua.components.optimizers import COBYLA, SPSA, SLSQP
from qiskit import IBMQ, BasicAer, Aer
from qiskit.chemistry.drivers import PySCFDriver, UnitsType
from qiskit.chemistry import FermionicOperator
from qiskit import IBMQ
from qiskit.providers.aer import noise
from qiskit.aqua import QuantumInstance
from qiskit.ignis.mitigation.measurement import CompleteMeasFitter
```
Another Error pops up at 

```python
qubitOp = qubitOp.two_qubit_reduction(num_particles)
``` 

Which moved to:

```python
from qiskit.aqua.operators import Z2Symmetries
qubitOp = Z2Symmetries.two_qubit_reduction(qubitOp, num_particles)
```

And finally, this parameter got deprecated:

```python
vqe = VQE(qubitOp, var_form, optimizer), 'matrix')
```
Which can be just dropped i guess (Deprecation Warning noted, that the Operator now takes care of that)

```python
vqe = VQE(qubitOp, var_form, optimizer))
```

Could anyone please confirm the correctness of my suggestions? Then i'm going to add a PR for that page (further down on the page, when doing it on ibmq, the same errors repeat).
