### ISSUE TITLE
Complete migration

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-textbook#20]

**Comment by 1ucian0** [comment]
As part of the migration, I suggest to dynamically generate the index. Something like this:
https://github.com/1ucian0/qiskit-textbook/blob/deploy/index/index.yaml

**Comment by delapuente** [comment]
When moving to Jupyter Book, this will be the default. See [toc.yaml](https://github.com/delapuente/qiskit-textbook/blob/jupyter-book/_data/toc.yml) at my branch.

**Comment by 1ucian0** [comment]
`index.html` currently contains more information than just the toc. Authors, date (and probably version in the near future). How to handle that?

**Comment by aasfaw** [comment]
Keep index to chapter/section links and author list + license + cover image. Something very similar to the yaml in @delapuente's branch, but with dynamic info for author list as well, as that will change as more people contribute.

**Comment by aasfaw** [comment]
@delapuente and @1ucian0 did a great job with this one -- thank you! Closing now
