### ISSUE TITLE
Allow Downloading Entire Textbook as PDF

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/qiskit-textbook#204]
## Describe the Issue
A few people have asked for a way to download the entire textbook as a pdf. There should be a single button to do this.

**Comment by dakk** [comment]
@frankharkins did you found a way to do that?

**Comment by Indeximal** [comment]
Did this ever get implemented? In my quest to do it myself I noticed the jupyter version used doesnt seem to support pdf creation.

**Comment by Zeinab-Rahmani** [comment]
Hello. Could we get the whole textbook as a pdf? That is really necessary. Thank you.

**Comment by ugurbolat** [comment]
Ping
