### ISSUE TITLE
Typo in 1.2

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit-textbook#206]
The code cell

```
n = 8
n_q = 8
n_b = 8
qc_output = QuantumCircuit(n_q,n_b)
```

should read

```
n = 8
n_q = n
n_b = n
qc_output = QuantumCircuit(n_q,n_b)
```
The idea is that we would normally just use `n=8` here in all cases. The `n_q` and `n_b` are only defined to explicitly show which arguments of `QuantumCircuit()` define which type of register.

@frankharkins This is one of many issues I'll be making as I go through and teach the textbook over the next few weeks. This one is not urgent, and I think most others will be the same.

**Comment by frankharkins** [comment]
@quantumjim thank you! I will get on it shortly.
