### ISSUE TITLE
Computing or computation?

### ISSUE THREAD

**Issue by abbycross** [Qiskit/qiskit-textbook#213]
## Describe the Issue

Title of textbook in image is different from title on page itself.

<img width="505" alt="Screen Shot 2020-02-21 at 9 49 12 PM" src="https://user-images.githubusercontent.com/28769477/75085120-04f2dd00-54f4-11ea-9d5e-358be9505c4d.png">

## Expected Solution

They should match.

**Comment by aasfaw** [comment]
Fixed jointly in PR #212
