### ISSUE TITLE
Add Binder, JupyterHub, or Thebelab links automatically for interactivity

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-textbook#223]
## Describe the Issue
The textbook pages on the website are static with no interactivity. 

## Expected Solution
Add Binder, JupyterHub, or Thebelab links automatically for interactivity. This is a feature of Jupyter book: https://jupyterbook.org/intro.html

**Comment by aasfaw** [comment]
This was already in the works -- Closed via #247 and thebelab

**Comment by HuangJunye** [comment]
Just curious, how does Qiskit run on the textbook website? Running on a remote server hosting Qiskit using flask?
