### ISSUE TITLE
Mixed conventions in images/superdense_table2.png (chap 3.2 superdense coding, step 2.3)

### ISSUE THREAD

**Issue by HTransistor** [Qiskit/qiskit-textbook#232]
## Describe the Issue
In the table images/superdense_table2.png the convention a) with |qubit0 qubit1> is used, even tough qiskit convention is b) with |qubit1 qubit0>.

In the first line |00> + |11> after CNOT(0,1) gets |00> + |01>,which is convention b).
In the other 3 lines convention a) is used.
For example line 2 is:
|01> + |10> after CNOT(0,1) gets |01> + |11>
## Expected Solution
Decide for convention one convention a) or b).
case a):
line 1 should be changed to:
|00> + |11> after CNOT(0,1) gets |00> + |10>
case b):
line 2,3,4 need to be changed
## Anything else we should know?
Make clear which convention a) or b) is used in the whole textbook.
Since qiskit uses b), I would suggest b) in the textbook, too.

**Comment by frankharkins** [comment]
Good spot! Thanks for pointing this out
