### ISSUE TITLE
Image not shown (missing html tags), (chap 3.2 superdense coding step2.2,2.3)

### ISSUE THREAD

**Issue by HTransistor** [Qiskit/qiskit-textbook#233]
## Describe the Issue
In step 2.2:
Instead of images in the html the following is shown:
"![image2] (images/superdense_table1.png)"

In step 2.3:
The subtitle is in the middle of the text:
"### 2.3 Step 3"

In the html there are no tags.
## Expected Solution
Add right tags.

**Comment by frankharkins** [comment]
Good spot! I've jiggled it around a bit, rebuilt the site and it seems to have fixed it. Thank you.
