### ISSUE TITLE
IBMQ.load_accounts()    [Deprecated]

### ISSUE THREAD

**Issue by MozammilQ** [Qiskit/qiskit-textbook#25]
While executing commands in accordance with this page...
https://community.qiskit.org/textbook/ch4/4.5.html

IBMQ.load_accounts()
is being deprecated
![loadaccount](https://user-images.githubusercontent.com/54737489/66270493-0dfb4e80-e872-11e9-9907-01e8e468db15.png)

**Comment by aasfaw** [comment]
Fixed by #28
