### ISSUE TITLE
hello_quantum module not found

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-textbook#260]
## Describe the Issue
Going to interactive mode in textbook problems set 0 - Hello Qiskit gives a module not found error for `import hello_quantum`

## Expected Solution
The needed packages are installed in the binder image.

**Comment by quantumjim** [comment]
Does the binder not support local imports? The file is [here](https://github.com/Qiskit/qiskit-textbook/blob/master/content/ch-ex/hello_quantum.py).

**Comment by frankharkins** [comment]
Fixed in PR#274
