### ISSUE TITLE
IBMQ.get_backend()  [Deprecated]

### ISSUE THREAD

**Issue by MozammilQ** [Qiskit/qiskit-textbook#27]
While executing commands in accordance with this page....
https://community.qiskit.org/textbook/ch4/4.5.html

IBMQ.get_backend()
is being deprecated 

![get_back](https://user-images.githubusercontent.com/54737489/66271040-2ae65080-e877-11e9-97a4-1a9cc60881af.png)

**Comment by aasfaw** [comment]
Fixed by #28
