### ISSUE TITLE
Typo in Proving Universality

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit-textbook#280]
## Describe the Issue

In [Proving Universality](https://github.com/Qiskit/qiskit-textbook/blob/master/content/ch-gates/proving-universality.ipynb)

> This suggests a naive approach to solving our problem: we could apply $R_z(a) = e^{i bZ}$ followed by $R_x(b) = e^{i a X}$.

Should be

> This suggests a naive approach to solving our problem: we could apply $R_z(2b) = e^{i bZ}$ followed by $R_x(2a) = e^{i a X}$.

**Comment by frankharkins** [comment]
Fixed in commit 800938796fb7adb81405438ed34d0a22f2867ab (forgot to add this to the commit message)
