### ISSUE TITLE
Unable to import qiskit_textbook from jupyter notebook

### ISSUE THREAD

**Issue by mriedem** [Qiskit/qiskit-textbook#284]
## Describe the Issue

With a recent change [1] I'm unable to import `qiskit_textbook` in a jupyter notebook. It appears to be because there is no `__init__.py` under that package.

We're installing by doing `pip install -r requirements.txt` from the `qiskit-textbook-src` directory.

[1] https://github.com/Qiskit/qiskit-textbook/commit/b81f279d23b0eb1457d475fec68e7cdf0af55654#r38077999

## Expected Solution

The refactor of the textbook package should be pip installable such that the `qiskit_textbook` package can be imported.

## Anything else we should know?

The weird thing is if I git clone this repo and do the same `pip install -r requirements.txt` then I'm able to start a python session and import the `qiskit_textbook` package so I'm not sure why that's different, but python packages should have an `__init__.py` in them regardless.

**Comment by quantumjim** [comment]
This still seems to be an issue. I can't run the Hello Qiskit notebook locally or in IQX.

**Comment by frankharkins** [comment]
locally you will need to run:
```
%%bash
cd ../../qiskit-textbook-src/
pip install -e .
```
In the notebook or otherwise install the package. Maybe we need to include instructions for local users?

I _believe_ it's installed on IQX too, but the fix is not currently pushed to the live version, maybe @mriedem can tell us more.

**Comment by mriedem** [comment]
> I _believe_ it's fixed on IQX too, but the fix is not currently pushed to the live version, maybe @mriedem can tell us more.

It's not yet working in IQX because of _this_ issue so once we're building with this fix then it should be working (I've been testing in our staging environment before pushing that all to production).

**Comment by Arkturiuz** [comment]
maybe run since anaconda prompt
