### ISSUE TITLE
Add three navigation links at the top and bottom of each html page (next, previous, index page)

### ISSUE THREAD

**Issue by der-datenzauberer** [Qiskit/qiskit-textbook#29]
Hi @aasfaw, 

Firstly I would like to appreciate the efforts of every active member of the Qiskit community. You guys are doing a commendable job !!!

Additionally I have a suggestion as below:-

This request is to add 3 navigation links like next, previous and index page at the **top and bottom of each page.** It will help to navigate through the chapters easily like a book.

**Comment by aasfaw** [comment]
Thanks @der-datenzauberer -- this is something we're working on incorporating at the moment. The new version of the textbook will be much easier to navigate.

**Comment by aasfaw** [comment]
I'll close this issue with the PR that makes this change. Thanks again @der-datenzauberer

**Comment by starktech23** [comment]
#37 might work for now. @aasfaw kindly take a look.

**Comment by delapuente** [comment]
After the migration to Jupyter Book, this is no longer an issue.
