### ISSUE TITLE
3.8grover mpl plot labeling wrong because of use of QuantumRegister

### ISSUE THREAD

**Issue by HTransistor** [Qiskit/qiskit-textbook#291]
## Describe the Issue
In mpl plots of the executed code the qubits labels get names like: qx_0, where x is the number of the executions of the code. This happens as  qr = QuantumRegister(2) doesn't give a list back anymore. Same for cr = ClassicalRegister(2)
A list is needed in QuantumCircuit(qr,cr).
## Expected Solution
Instead of using `QuantumRegister(2).__len__() `and then dealing with range, define qr = [0,1,2], cr = [0,1,2] and use QuantumCircuit(3,3).
Is there a reason to use QuantumRegisters in the first place?

![grover_qubit_label](https://user-images.githubusercontent.com/43704364/77854372-401ab700-71ea-11ea-8a48-6cdeb9a39bc8.png)

## Anything else we should know?
Probably a bug that should even be fixed in qiskit itself (if the use of QuantumRegister is inevitable).
PS: I reported the bug in qiskit/terra, nethertheless I think the qiskit-textbook should just use lists instead of registers in QuantumCircuit().

**Comment by HTransistor** [comment]
It turned out, it was a missing documentation of QuantumRegister() and ClassicalRegister(): when QuantumRegister(2, 'q') used everything is fine.

**Comment by frankharkins** [comment]
@HTransistor, yes you are right, there is no reason to use `QuantumRegister` and `ClassicalRegister`, we can actually just use `QuantumCircuit(2)` and `.measure_all()`. I notice you have made the PR #298, so if you want to, you can change the code to remove the `qr` / `cr` bit. If not I'm happy to do it.

**Comment by frankharkins** [comment]
Actually, the above comment is true for chapters 3.4 and 3.8, but I think you need separate registers to apply the controlled gate (`circ.append(cgrit, qargs=[qubit] + qreg[4:])`). I could be wrong here.

**Comment by frankharkins** [comment]
@HTransistor, in response to your slack message, the PR does fix the plots, but a better fix is giving QuantumCircuit two integers and letting it create the register instead of creating two registers separately. If you want to make this change then let me know, otherwise I can do it.

**Comment by HTransistor** [comment]
Alright. I will make the changes.

**Comment by frankharkins** [comment]
Thank you!
