### ISSUE TITLE
3.7qpe qiskit convention of numbering qubits in circuits and brakets

### ISSUE THREAD

**Issue by HTransistor** [Qiskit/qiskit-textbook#296]
## Describe the Issue
Qiskit convention of numbering qubits from top to bottom and in from right to left in brakets.
Whole chapter is using mixed conventions.

In the picture the U^2^(n-1) is controlled by qubit 0.
![qpe_overview](https://user-images.githubusercontent.com/43704364/77900027-b7e5f180-727d-11ea-81fd-d3ac24b708b9.png)

In the formula qubit 0 should be most right one, so U^2^(n-1) should be applied, instead U^2^0 is applied. Is the QFT shown in qiskit convention?
![qpe_overview1 2](https://user-images.githubusercontent.com/43704364/77901086-4c048880-727f-11ea-8397-d95e67927200.png)

Here U^2^0 is applied to qubit 0, contrary to the first picture.
![qpe_2_1](https://user-images.githubusercontent.com/43704364/77901601-288e0d80-7280-11ea-8053-1dd0f91679ae.png)

Interesting enough in 3.2 the qiskit convention is used.
![qpe_3_2_right](https://user-images.githubusercontent.com/43704364/77901574-1c09b500-7280-11ea-8f9b-8b18329fe799.png)

But in 4 again not
![qpe_4](https://user-images.githubusercontent.com/43704364/77901859-95a1a300-7280-11ea-8166-d421fcc089c3.png)

## Expected Solution
Use qiskit convention in all circuits and formulas.
First correct the first circuit to qiskit convention (make sure how the quantum phase estimation circuit looks in qiskit convention), then correct all formulas and pictures accordingly. Also make sure the QFT is used in qiskit convention.

## Anything else we should know?
As this convention issue appears over and over, the convention should be mentioned at the top of each chapter as a reminder. Moreover using circuit diagrams from other sources than qiskit is dangerous and should be avoided. Probably this hint is fair enough to put in the README.

**Comment by frankharkins** [comment]
Good spot with 3.2, for some reason it gives the same answer even though it is technically the wrong way round. I think using circuit diagrams with other conventions is fine as long as it is clearly mentioned that qiskit uses a different convention. Especially with the equations, these can be quite messy if we start changing the qubit ordering around.

**Comment by HTransistor** [comment]
Okay when you want to stay with circuits for explaining in "normal" convention, and implemented circuits in "qiskit" convention, why then in 3.9Quantum Coding section 1.2 in the explaining part the qiskit convention is used right from the beginning? (So it is contrary to the explanation picture from qpe in 1.overview as screenshoted in the first comment)
![quantum_coding_1_2_convention](https://user-images.githubusercontent.com/43704364/79003641-49454580-7b53-11ea-8d57-2bc064c75579.png)
