### ISSUE TITLE
Broken links in chapter 0.2 Qiskit

### ISSUE THREAD

**Issue by kifumi** [Qiskit/qiskit-textbook#297]
## Describe the Issue
Two links are broken in chapter 0.2 Qiskit (https://qiskit.org/textbook/ch-prerequisites/qiskit.html);

1. Introduction to Python and Jupyter notebooks
2. Chapter 1

**Comment by frankharkins** [comment]
@kifumi, is the problem that you cannot actually click the links, as opposed to them leading to the wrong url?

**Comment by kifumi** [comment]
@frankharkins , yes, the words are blue but I cannot click.

**Comment by frankharkins** [comment]
This seems to be a css problem and should be fixed when I merge the `styling` branch. Thanks for spotting it!
