### ISSUE TITLE
Addition of Shor's algorithm

### ISSUE THREAD

**Issue by RohanBh** [Qiskit/qiskit-textbook#3]
The [upcoming topics][1] section of the textbook contains Shor's algorithm. Is someone working on adding this topic? If not, can I proceed to work on this topic and create a PR for the same?

[1]: https://community.qiskit.org/textbook/ch-upcoming/0.html

**Comment by aasfaw** [comment]
Hi @RohanBh, the upcoming topics have already been assigned. However, if you do think of any topics outside that list or an improvement on any of the current sections, please feel free to open a pull request. Looking forward to seeing your contribution.
