### ISSUE TITLE
1.3 Observer Effect Typo 

### ISSUE THREAD

**Issue by KeyboardMonkey221** [Qiskit/qiskit-textbook#320]
## Describe the Issue
The initial_state set in the variable does not match what is computed below in the qc.draw() result.

![Screen Shot 2020-04-06 at 1 21 04 pm](https://user-images.githubusercontent.com/37201750/78520365-a8305500-7809-11ea-805e-1b6ce1a73c74.png)

Is this a typo?

**Comment by frankharkins** [comment]
@KeyboardMonkey221, thanks for pointing this out. This is an example of global phase being ignored by Qiskit. It is mentioned in the next paragraph, but this post has made me realise I need to clarify this earlier.

**Comment by frankharkins** [comment]
@KeyboardMonkey221 I apologise, actually yes this is a typo! The two states do not differ by global phase as a claimed in the comment above, the issue was a spelling mistake with the variable names. I have fixed this now and will merge shortly.
