### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-textbook#325]
## Describe the Issue
Searching "circuit" does nothing.

## Expected Solution
Search works

**Comment by frankharkins** [comment]
Seems to be working for me. How are you viewing the textbook?

**Comment by quantumjim** [comment]
I use Firefox on OSX and search doesn't work for me either. I enter the search term, press return and nothing happens.

**Comment by nonhermitian** [comment]
Yes same. Also search on iphone does nothing.
