### ISSUE TITLE
Issues in Bernstein-Vazirani

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit-textbook#337]
## Describe the Issue

1a
* The bit strings in are not expressed in the standard Qiskit order.
* The notation for strings in is strange.
* There is mention 

1b
* The use of 𝑥=1,2,… refers to the number represented by a string. In 1a we only referred to the string itself. Is there any need to refer to the number?
* Reference to the 'hidden integer', despite other mentions being as 'hidden string'.
* Oracle is not explained.
* Hidden string is called a in the discussion of the classical method, and s elsewhere.

## Expected Solution

I have fixed the issues in the fork for my course (see [here](https://nbviewer.jupyter.org/github/quantumjim/Quantum-information-course-Basel/blob/master/qiskit-textbook/content/ch-algorithms/bernstein-vazirani.ipynb)). Perhaps some elements (or all) could be used in the textbook.

**Comment by frankharkins** [comment]
I believe this is fixed in a7ff6935a46ec250d773f893c38bcc5c066f3033
