### ISSUE TITLE
QFT using Qiskit's reversed order of qubits

### ISSUE THREAD

**Issue by ebaeumer** [Qiskit/qiskit-textbook#34]
Since qiskit reverses the order of the qubits, one has to make sure to always reverse the states before putting them into the formula \sum_j e^{2 \pi i * j * x / N}, 
e.g. QFT |100> = \sum_j e^{2 \pi i * j * **1** / N} |j>, so here x = 1 = (001).
I think this is currently wrong in the textbook, as it says "acting on state |x> = |x_1 ... x_n>, where x_1 is the most significant bit", while x_1 would be the least significant bit here I believe (also, why is it not x_0?).
Apart from that, I think we should also stress that it is important to FIRST reorder, i.e. one cannot just reverse the output bits (e.g. when taking the QFT of (001) and (100) one gets in both cases a superposition of all states, but with different relative phases, so reversing the output bits does not help)! 
The whole reverse ordering becomes particularly bad when given a state-vector. To apply the QFT we need the vector (x_0, x_1, x_2, …, x_{N-1}) of a given state |\psi>= \sum_j x_j |j>, which  in “standard textbook-notation” just corresponds to the state vector. In qiskit, however, the state vector e.g. on three qubits would then correspond to (x_0, x_4, x_2, x_6, x_1, x_5, x_3, x_7). Therefore, I think it's important that we stress that when given a state |\psi> or a state vector (a_0, a_1, a_2, ...) in qiskit formalism, one first needs to determine the amplitude vector x = (x_0, x_1, x_1, ..., x_{N-1}) of the "reversed" (= "textbook-ordered") state to "feed" to the QFT (which is in general non-trivial).

**Comment by ebaeumer** [comment]
Also, I recognized now that the output one gets when running the qft() function with qiskit (as defined in section 7) is in "standard textbook notation", which means that one could not use the output state vector for further calculations, but first needs to transform it such that all qubits are again in reversed order. While it is indeed mentioned that the order of the output qubits of the circuit is reversed, I think one should add a transformation already in the qft() function, such that e.g. applying qft() twice gives the correct state (right now this is not the case due to the reverse order). Also, in the example the expected result should be in standard notation state "001", so in qiskit we would like to get the counts for the state "100" instead...

**Comment by esobimpe** [comment]
@aasfaw @ebaeumer can I go ahead and fix this issue?

**Comment by ebaeumer** [comment]
I already did a pull request for that one...

**Comment by esobimpe** [comment]
That makes sense

**Comment by aasfaw** [comment]
Wahoo! Thanks @ebaeumer @esobimpe @frankharkins
