### ISSUE TITLE
2.5.4 "The Toffoli" probable typo

### ISSUE THREAD

**Issue by Looka13** [Qiskit/qiskit-textbook#351]
## Describe the Issue
From visual inspection and my current understanding of the topic it seems that the second snippet of code (implementing controlled-controlled-U) of the section 2.5.4 ("[The Toffoli](https://qiskit.org/textbook/ch-gates/more-circuit-identities.html#4.-The-Toffoli-)") of the textbook is not correct.
Moreover it is not consistent with the image reported below the code.

## Expected Solution
I think it should be changed from:

```
qc = QuantumCircuit(3)
qc.cu1(theta,b,t)
qc.cx(a,b)
qc.cu1(-theta,b,t)
qc.cx(a,b)
qc.cu1(theta,b,t)    <-
qc.draw()
```

To:

```
qc = QuantumCircuit(3)
qc.cu1(theta,b,t)
qc.cx(a,b)
qc.cu1(-theta,b,t)
qc.cx(a,b)
qc.cu1(theta,a,t)    <-
qc.draw()
```

**Comment by aditya-giri** [comment]
This was fixed in PR #357, you can close this.
