### ISSUE TITLE
QFT chapter uses CROT instead of UROT

### ISSUE THREAD

**Issue by aditya-giri** [Qiskit/qiskit-textbook#393]
## Describe the Issue

Given that in the QFT chapter the UROT gate is defined as a single qubit gate, and the CROT gate is defined as a conditional UROT gate, the circuits (and some of the text) in the QFT chapter are incorrect.

For example, in the image below, the gates should really be UROT and not CROT, the same way a CX gate is represented by a dot on the control qubit and an X gate (and not a CX gate) on the target.
![image](https://user-images.githubusercontent.com/30208735/82729966-db776680-9d19-11ea-8590-30f1bed837b8.png)

I also believe that text like:
```After the CROT2 gate on qubit 1 controlled by qubit 2, the state is transformed to …```
should ideally be written:
```After the UROT2 gate on qubit 1 controlled by qubit 2, the state is transformed to …```
but I understand that this is debatable and can be understood either way.

EDIT: Also, the last qubit seems to be missing a H gate.

PS: I'll pick this up :)

**Comment by aditya-giri** [comment]
@frankharkins I was wondering how the image was generated so that I can replicate it

**Comment by frankharkins** [comment]
@aditya-giri I am not sure about this image, I create mine using the qcircuit package in LaTex, although be warned this can be quite fiddly and time consuming. I know qiskit can output images to LaTeX (not sure exactly how it does this) but you may be able to use it as a starting point. If you are competent with GIMP or Photoshop you may find it easier to simply adjust the existing image.

**Comment by aditya-giri** [comment]
@frankharkins as it turns out, Paint 3D on Windows was all it took... 🤷‍♂️
