### ISSUE TITLE
Sec 3.10 uses old register format.

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-textbook#398]
Sec 3.10 uses old register format, e.g.

```python

qreg = QuantumRegister(8, 'q')   # First 4 are for counting, last 4 for 'searching'
t = 4   # no. of counting qubits
n = 4   # no. of searching qubits
creg = ClassicalRegister(4, 'c')
circ = QuantumCircuit(qreg, creg)
```

**Comment by quantumjim** [comment]
I don't know if it should be called the 'old format'. As far as I know, it's the only format to use when we need to specify different registers.

In this section, the explanation uses the notion of there being two qubit registers. So it would make sense to use this notion in the circuit too. However, the circuit actually only uses one register (combining the two), but nevertheless doesn't use the shortened form to declare it.

So there is indeed something that needs to be changed here. Either we keep the circuit with a single qubit register, but change to the shortened form of declaration. Or we use two qubit registers (as in the explanation).

**Comment by frankharkins** [comment]
I agree that there are a few places in the textbook where the circuits could be made clearer using multiple QuantumRegisters. Some feedback on the Deutsch-Joza chapter was that the reader forgot which qubits were the 'input' qubits and which the 'output' qubit. I'm sure this can extend to other algorithms such as this one.
