### ISSUE TITLE
Lost first paragraph in 2.3 Phase Kickback

### ISSUE THREAD

**Issue by ikkoham** [Qiskit/qiskit-textbook#422]
## Describe the Issue

The following paragraph is not found in the [website](https://qiskit.org/textbook/ch-gates/phase-kickback.html).

> 
> 1. Exploring the CNOT-Gate
> 
> In the previous section, we saw some very basic results with the CNOT gate. Here we will explore some more interesting results.
> 
> We saw that we could entangle the two qubits by placing the control qubit in the state $|+\rangle$:
> $$ \text{CNOT}|0{+}\rangle = \tfrac{1}{\sqrt{2}}(|00\rangle + |11\rangle) $$
> 
> But what happens if we put the second qubit in superposition?

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/6814928/83414671-db354480-a458-11ea-9f65-29865612addd.png">

## Anything else we should know?

I use macOS and Firefox.

**Comment by frankharkins** [comment]
Good spot, thank you! This is an issue with the cell tags in the notebook.

**Comment by ikkoham** [comment]
Thanks for quick response, but I do not think it is fixed yet.

**Comment by ikkoham** [comment]
Now, I check its fixed.
