### ISSUE TITLE
First Qiskit examples throw an error

### ISSUE THREAD

**Issue by asierarranz** [Qiskit/qiskit-textbook#436]
## Describe the Issue
The first example is throwing an error, to replicate it navigate to:
https://qiskit.org/textbook/ch-states/representing-qubit-states.html
Click Try&Run on the 3 code snipets and wait for the error.

`AttributeError: 'Initialize' object has no attribute 'label'
`
## Expected Solution
Qiskit code executing without errors

**Comment by jwoehr** [comment]
Known issue. See:
- https://github.com/Qiskit/qiskit-terra/issues/4439
- https://github.com/Qiskit/qiskit-terra/pull/4389
