### ISSUE TITLE
Required prerequisites for 'proving universality' are no longer in the ToC

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit-textbook#443]
The 'proving universality' section was written with the assumption that [fun with matrices](https://github.com/Qiskit/qiskit-textbook/blob/master/content/ch-gates/fun-matrices.ipynb) and [the standard gate set](https://github.com/Qiskit/qiskit-textbook/blob/master/content/ch-gates/proving-universality.ipynb) would be read first, but these are no longer in the table of contents.

Specifically, we are missing:

* The fact that `rx` gates can be expressed $R_x(\theta) = e^{i \frac{\theta}{2} X}$.
* The fact that any matrix can be written in terms of Paulis.

I'll have a go at scraping the required content out of the deprecated sections, and putting them into an extended 'proving universality'.

**Comment by HwajungKang** [comment]
I totally agree! actually was gonna ask about it after noticing bunch of stuff that I saw in the past disappeared which disconnect the content to the 'proving universality' section.
 
----- Original message -----From: James Wootton <notifications@github.com>To: Qiskit/qiskit-textbook <qiskit-textbook@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [EXTERNAL] [Qiskit/qiskit-textbook] Required prerequisites for 'proving universality' are no longer in the ToC (#443)Date: Thu, Jun 11, 2020 5:04 AM 
 
The 'proving universality' section was written with the assumption that fun with matrices and the standard gate set would be read first, but these are no longer in the table of contents.
Specifically, we are missing:
        The fact that rx gates can be expressed $R_x(\theta) = e^{i \frac{\theta}{2} X}$.        The fact that any matrix can be written in terms of Paulis.
I'll have a go at scraping the required content out of the deprecated sections, and putting them into an extended 'proving universality'.
