### ISSUE TITLE
Error with the link to one reference in Shor chapter

### ISSUE THREAD

**Issue by sergio-tello** [Qiskit/qiskit-textbook#456]
## Describe the Issue
Clicking on the link to Beauregard's paper in the References section of the Shor algorithm chapter takes you nowhere.
## Expected Solution
Change the markdown code providing the link to the paper in the arxiv.
## Anything else we should know?
Already fixed the issue in my forked qiskit-textbook repo - Shor_references branch. Can I create a PR?

**Comment by frankharkins** [comment]
Hi Sergio, yes please make a PR. Thanks for spotting this and then going the extra mile and fixing it.

**Comment by sergio-tello** [comment]
Thank you, Frank!
