### ISSUE TITLE
Minor grammar mistakes

### ISSUE THREAD

**Issue by deadmau6** [Qiskit/qiskit-textbook#46]
I found a few grammar mistakes in Chapter 0.2.
`line 133: ..."We perform this process until was have used all rows of the first matrix."`
`line 472: ... "This is fact very powerful"`
Also I think there is a mistake in `line: 459`, the B^(2n+1) is still in the sum on the reduction side of the equation. If some one could double check to make sure that I am not mistaken that would be awesome.

Now these could easily be corrected right now, or maybe we could wait and see if any more mistakes pop up and then fix everything all in one push? What do you all think? It would be cool if there was a feedback or reporting mechanism(but that is for another issue).

Either way could I make the fixes? This feels like a good `first time` issue, and I am trying to get more involved with the tools I use.

**Comment by quantumjim** [comment]
Thanks!

Please do have a go at fixing any issues you find!
