### ISSUE TITLE
Solving Combinatorial Optimization Problems using QAOA

### ISSUE THREAD

**Issue by Lucaman99** [Qiskit/qiskit-textbook#5]
The section of the textbook entitled "Solving Combinatorial Optimization Problems using QAOA" still needs to be completed. If nobody is currently working on this, I would love to!

**Comment by aasfaw** [comment]
Hi! Thank you for asking -- someone is already working on that section. This, as well as the items in the "Upcoming topics" list are currently assigned to someone. If you would like to work on any other sections, you are more than welcome to do this.
