### ISSUE TITLE
Qiskit Introduction in Chapter 0

### ISSUE THREAD

**Issue by leimao** [Qiskit/qiskit-textbook#53]
I am not sure how others felt. I personally felt the appearance of Qiskit introduction in Chapter 0 is too absurd. It is hard to understand for a noob.

**Comment by quantumjim** [comment]
Thanks for the comment.

What exactly is the issue you are having? Is it simply that the Qiskit intro appears in Chapter 0, or is it the content of the chapter?

The reason for it being in Chapter 0 is that it is not the purpose of the textbook to teach Qiskit, but rather to teach quantum computation through the medium of Qiskit. Just as it does not aim to teach Python, but just to use Python. It is for that reason that a quick intro is given before Chapter 1.

**Comment by leimao** [comment]
When I first read the Qiskit Introduction in Chapter 0, because there are many quantum related terminology, such as quantum circuit, and a lot of quantum operations which would be used in the later chapters. Since the reader has not known what those quantum related things when we are using Chapter 0, correlate the Python code with the actual physics is hard. Personally I think this should not be a prerequisite, and Qiskit should be taught as we learned quantum computing step by step. I just finished reading Chapter 1.1, and I felt a little bit more comfortable with programming with Qiskit. But when I take a look back at Chapter 0.1 Qiskit, I still have no idea what most of the code are doing.

**Comment by leimao** [comment]
The math part in the introduction, however, is good. It is concise and it does not lack basic derivations and proofs.

**Comment by quantumjim** [comment]
Okay, I see what you mean.

The Chapter 0 Qiskit intro is really designed for people who already know quantum circuits, states and gates, and just want to know the Qiskit syntax before looking at the later chapters. We should include a note to make sure the reader knows this.

Chapter 1 should really introduce Qiskit as it goes along. It seems to lack that at the moment, due to some historical reasons. So I'll make some changes to make that happen.

**Comment by leimao** [comment]
Thanks @quantumjim . As a noob, I will keep reading through and provide feedback. Use your best judgement to decide whether you should make a change or not :)

**Comment by quantumjim** [comment]
Thanks for the feedback!
