### ISSUE TITLE
chapter calibrating-qubits-openpulse, Compatibility issues with qiskit 0.13 

### ISSUE THREAD

**Issue by sudhakarsq** [Qiskit/qiskit-textbook#57]
Problem in executing following cell:
![image](https://user-images.githubusercontent.com/4879686/67611639-21128780-f769-11e9-86f7-91d51a0c4e9c.png)

**Comment by sudhakarsq** [comment]
Also, this method is depracated.

![image](https://user-images.githubusercontent.com/4879686/67612604-ebbe6780-f771-11e9-9e11-fd4d3cc3ce53.png)

**Comment by sudhakarsq** [comment]
For the changes noted above and a couple others, I made corresponding edits to the notebook which are captured in the following pull request:

https://github.com/Qiskit/qiskit-textbook/pull/59

**Comment by aasfaw** [comment]
This has been fixed by PR #101. Thanks @sudhakarsq
