### ISSUE TITLE
semantics error in coding with atoms of computations

### ISSUE THREAD

**Issue by DaxedLuffy** [Qiskit/qiskit-textbook#60]
The highlighted text should be **(3,1)** instead. The next line has a similar code with the correct semantics. I am learning through this book if its a bug I would be more than happy to debug it. seems like a **good first issue.**

https://community.qiskit.org/textbook/ch-states/atoms-computation.html

![image](https://user-images.githubusercontent.com/50601580/67715129-37ca1000-f9ef-11e9-98ae-147b20d01054.png)

**Comment by frankharkins** [comment]
Fixed, thank you!
