### ISSUE TITLE
grammer issues in /ch-prerequisites-linear_algebra

### ISSUE THREAD

**Issue by DaxedLuffy** [Qiskit/qiskit-textbook#61]
I have identified **several grammar mistakes** on this page (https://community.qiskit.org/textbook/ch-prerequisites/linear_algebra.html) and other pages. can I rectify these?
![image](https://user-images.githubusercontent.com/50601580/67716498-f1c27b80-f9f1-11e9-90d7-84e8ff4784c2.png)

**Comment by mrthankyou** [comment]
I am not a maintainer nor contributor for this repo, but I would say that you should be able to submit a PR with grammar fixes. From the readme:

> Contributions of all types are always welcome. Please start a pull request to submit changes, or create an issue to request updates.
