### ISSUE TITLE
New topic for the textbook

### ISSUE THREAD

**Issue by esobimpe** [Qiskit/qiskit-textbook#62]
Can someone take a look at PR #47... Is it something we wanna add to qiskit textbook  and what's it missing?

**Comment by DaxedLuffy** [comment]
![image](https://user-images.githubusercontent.com/50601580/67801262-d2d5ef00-faae-11e9-9040-59234fa91d62.png)
### Besides these highlighted texts,  I found it quite well written and easily understandable!

**Comment by esobimpe** [comment]
@DaxedLuffy Thanks for your comment, highlighted errors have been corrected. Let me know if you have any other comments. Are you also one of the IBM people?

**Comment by DaxedLuffy** [comment]
**@esobimpe** You're welcome! No, I am not from IBM. Just an enthusiast! 

![image](https://user-images.githubusercontent.com/50601580/67932130-614e8b80-fbe9-11e9-80d2-661d9bf5fe77.png)

You should just use this image and not include its code as it would not work for obvious reasons for someone using the Jupyter notebook in the local kernel.

**Comment by esobimpe** [comment]
That's true @DaxedLuffy. Will do that now

**Comment by esobimpe** [comment]
Besides, I think the image is not really necessary

**Comment by DaxedLuffy** [comment]
@esobimpe you used your **personal API,** you don't wanna do that! 
![image](https://user-images.githubusercontent.com/50601580/67934117-336b4600-fbed-11e9-8d2f-5aa05a33909b.png)

**Comment by esobimpe** [comment]
@DaxedLuffy but I won't be able to run it on a real quantum computer if i don't do that. I will remove it, but is there a way to run it and still get the plots without the api

**Comment by frankharkins** [comment]
@esobimpe, thank you! I have made some changes and merged it in.
