### ISSUE TITLE
Cheatsheet - Quantum gate matrix memorization 

### ISSUE THREAD

**Issue by der-datenzauberer** [Qiskit/qiskit-textbook#66]
Hi @aasfaw ,

Hope you are doing well. As a beginner, I often used to face difficulty in memorizing the matrix representation of the unitary operators. I am sure, most beginners will be facing this difficulty, especially if they are not engaged with the text very often.

As a result of this, every time I had to revisit the gates, as I would often mix things up e.g. like getting confused between phase gate and other gates. 

I created this cheat sheet today as a permanent remedy to my recurring problem. I feel this can help other learners as well.

I know it's not much of a  contribution, but this will give me confidence that in spite of being a beginner, I too can start small and slowly contribute and do more than creating issues only.

I therefore request you to please review it and include it somewhere in the textbook, if the team finds it useful
![image](https://user-images.githubusercontent.com/11174526/68088941-0f786080-fe8a-11e9-986e-051d739f74d9.png)

![image](https://user-images.githubusercontent.com/11174526/68089142-e3f67580-fe8b-11e9-94a0-a3516157f6f6.png)

![image](https://user-images.githubusercontent.com/11174526/68089147-f670af00-fe8b-11e9-9b7e-bef4c41047cf.png)

![image](https://user-images.githubusercontent.com/11174526/68089163-0be5d900-fe8c-11e9-96c3-faef113cd257.png)

**Comment by aasfaw** [comment]
This is a nice set of mnemonics @der-datenzauberer. Can you please create a folder called `ch-appendices` in `content/` and submit this image in a notebook named `cheatsheet_memorizing_quantum_gate_matrices.ipynb` in that folder, with some description of how to use the cheatsheet within the notebook?
