### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by ryzbaka** [Qiskit/qiskit-textbook#76]
On the html page for Chapter 1.0, the link at the bottom to 'Introduction to Linear Algebra for Quantum Computing' reroutes to https://community.qiskit.org/textbook/ch-prerequisites/linear_algebra.ipynb when it should actually go to https://community.qiskit.org/textbook/ch-prerequisites/linear_algebra.html .

**Comment by delapuente** [comment]
After migrating to Jupyter Book, this is no longer an issue. Closing.
