### ISSUE TITLE
Should y and z be stylized as the other bases?

### ISSUE THREAD

**Issue by 1ethanhansen** [Qiskit/qiskit-textbook#84]
In [standard-gate-set](https://github.com/Qiskit/qiskit-textbook/blob/master/content/ch-gates/standard-gate-set.ipynb) under Clifford gates, there is a section that reads:

> This has a similar effect to the Hadamard, except that it swaps $X$ and $Y$ instead of $X$ and $Z$. In combination with the Hadamard, we could then make a composite gate that shifts information between y and z. This therefore gives us full control over single-qubit Paulis.

Should the 'y' and 'z' at the end there be stylized as $Y$ and $Z$? Or am I mistaken and they are referring to something else?

The same question applies down further under 'Non-Clifford Gates' where it says:

> Certain examples of these rotations have specific names. Rotations by 𝜃=𝜋 around the x, y and z axes are X, Y and Z, respectively. Rotations by 𝜃=±𝜋/2 around the z axis are 𝑆 and 𝑆†, and rotations by 𝜃=±𝜋/4 around the z axis are 𝑇 and 𝑇†.

Shouldn't the capital 'X', 'Y', and 'Z' be $X$, $Y$, and $Z$, respectively?

**Comment by quantumjim** [comment]
I think the convention should be that the gates use latex. But the axes of the Bloch sphere are separate to the gates (though obviously related), so they use lower case instead.

**Comment by frankharkins** [comment]
I think these few paragrahs could be a bit confusing, I might rewrite and add some illustrations?

**Comment by frankharkins** [comment]
I think we will go with @quantumjim's convention.
