### ISSUE TITLE
Introduction to Python and Jupyter notebooks URL dead

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit-textbook#93]
The "Introduction to Python and Jupyter notebooks" https://community.qiskit.org/textbook/ch-prerequisites/python-and-jupyter-notebooks.ipynb is dead and so is https://community.qiskit.org/textbook/ch-states/introduction.html. This is linked from here: https://community.qiskit.org/textbook/ch-states/introduction.html

**Comment by mrthankyou** [comment]
@lerongil 

It appears you fixed this issue in #94. We can now close this issue. I would do it myself but I don't have the ability to do so. :(

**Comment by frankharkins** [comment]
Can confirm it's fixed now
