### ISSUE TITLE
Broken link in IBM experience website

### ISSUE THREAD

**Issue by dadhichi1** [Qiskit/qiskit-textbook#96]
"[Introduction to quantum circuit](https://quantum-computing.ibm.com/support/guides/introduction-to-quantum-circuits?section=5cae61e066c1694be21df8d0)" page end with what next ,
that link is broken, currently its going to staging .

ideally, it should point to following link 
https://quantum-computing.ibm.com/support/guides/5cb244d4bff8a7004cdfee42?section=5cbaf03974a4010049e1a2a9#

**Comment by mrthankyou** [comment]
There has been a recent update to the UI as I no longer am able to find the "What's Next" link. Therefore, I suggest this issue should be closed as it's not reproducible.
